<a href="https://colab.research.google.com/github/RCNXV/Gaming-Industry-Growth/blob/main/DAMC_2_Game_Sales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#File Unloading

In [2]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

In [3]:
game_sales = pd.read_csv('/content/drive/MyDrive/Kerja/DA/Portofolio/DAMC 2/dataset/Games Sales - Case Study - Games.csv')
game_sales.head()

,Name,Sales,Series,Release,Genre,Developer,Publisher
0,PlayerUnknown's Battlegrounds,42.0,NaN,12/1/2017,Battle royale,PUBG Studios,Krafton
1,Minecraft,33.0,Minecraft,11/1/2011,"Sandbox, survival",Mojang Studios,Mojang Studios
2,Diablo III,20.0,Diablo,5/1/2012,Action role-playing,Blizzard Entertainment,Blizzard Entertainment
3,Garry's Mod,20.0,NaN,11/1/2006,Sandbox,Facepunch Studios,Valve
4,Terraria,17.2,NaN,5/1/2011,Action-adventure,Re-Logic,Re-Logic

In [4]:
game_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 177 entries, 0 to 176
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       177 non-null    object
 1   Sales      177 non-null    float64
 2   Series     141 non-null    object
 3   Release    177 non-null    object
 4   Genre      177 non-null    object
 5   Developer  177 non-null    object
 6   Publisher  177 non-null    object
dtypes: float64(1), object(6)
memory usage: 9.8+ KB

#Data Cleaning

1. Change the datatype

  'Release' column wrong data type. it must in datetime64, not in object.

In [5]:
gsc = game_sales.copy()

In [6]:
gsc['Release'] = pd.to_datetime(gsc['Release'])
gsc.head()

,Name,Sales,Series,Release,Genre,Developer,Publisher
0,PlayerUnknown's Battlegrounds,42.0,NaN,2017-12-01,Battle royale,PUBG Studios,Krafton
1,Minecraft,33.0,Minecraft,2011-11-01,"Sandbox, survival",Mojang Studios,Mojang Studios
2,Diablo III,20.0,Diablo,2012-05-01,Action role-playing,Blizzard Entertainment,Blizzard Entertainment
3,Garry's Mod,20.0,NaN,2006-11-01,Sandbox,Facepunch Studios,Valve
4,Terraria,17.2,NaN,2011-05-01,Action-adventure,Re-Logic,Re-Logic

In [7]:
gsc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 177 entries, 0 to 176
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       177 non-null    object
 1   Sales      177 non-null    float64
 2   Series     141 non-null    object
 3   Release    177 non-null    datetime64[ns]
 4   Genre      177 non-null    object
 5   Developer  177 non-null    object
 6   Publisher  177 non-null    object
dtypes: datetime64[ns](1), float64(1), object(5)
memory usage: 9.8+ KB

2. Remove Duplicated Data

In [8]:
gsc = gsc.drop_duplicates()
gsc.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 175 entries, 0 to 174
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       175 non-null    object
 1   Sales      175 non-null    float64
 2   Series     139 non-null    object
 3   Release    175 non-null    datetime64[ns]
 4   Genre      175 non-null    object
 5   Developer  175 non-null    object
 6   Publisher  175 non-null    object
dtypes: datetime64[ns](1), float64(1), object(5)
memory usage: 10.9+ KB

3. Handling Missing Value

In [9]:
gsc.isna().sum()

Name          0
Sales         0
Series       36
Release       0
Genre         0
Developer     0
Publisher     0
dtype: int64

There is missing value in 'Series' column, we can see that because the game is in the first edition, so that they don't have series. We can change the missing value by its name of the game, instead of removing it.

In [10]:
updated_df = gsc.copy()
updated_df['Series'].fillna(updated_df['Name'], inplace=True)

# Filter the rows where 'Series' has been replaced
replaced_rows = updated_df[updated_df['Series'] != gsc['Series']]

# Print the replaced rows
replaced_rows[['Name','Series']]

,Name,Series
0,PlayerUnknown's Battlegrounds,PlayerUnknown's Battlegrounds
3,Garry's Mod,Garry's Mod
4,Terraria,Terraria
10,Fall Guys,Fall Guys
13,Rust,Rust
20,Valheim,Valheim
23,Cities: Skylines,Cities: Skylines
26,The Forest,The Forest
27,Cyberpunk 2077,Cyberpunk 2077
28,DayZ,DayZ
49,Factorio,Factorio
72,Magicka,Magicka
74,Planet Coaster,Planet Coaster
78,Space Engineers,Space Engineers
80,Stickfight: The Game,Stickfight: The Game
82,The Binding of Isaac,The Binding of Isaac
90,Stellaris,Stellaris
92,Satisfactory,Satisfactory
96,Kingdom Come: Deliverance,Kingdom Come: Deliverance
103,Blade Runner,Blade Runner
112,Cuphead,Cuphead
119,Dungeon Lords,Dungeon Lords
124,Full Throttle,Full Throttle
125,Glory of the Roman Empire,Glory of the Roman Empire
131,Hollow Knight,Hollow Knight
132,Hotel Giant,Hotel Giant
134,Imperivm: Great Battles of Rome,Imperivm: Great Battles of Rome
135,Just Survive[e],Just Survive[e]
136,Killing Floor,Killing Floor
137,Machinarium,Machinarium
139,Mordhau,Mordhau
140,Operation Flashpoint: Cold War Crisis,Operation Flashpoint: Cold War Crisis
143,Prison Architect,Prison Architect
159,Stardew Valley,Stardew Valley
165,The Stanley Parable,The Stanley Parable
172,Who Wants to Be a Millionaire?,Who Wants to Be a Millionaire?

In [11]:
gsc = updated_df
gsc.isna().sum()

Name         0
Sales        0
Series       0
Release      0
Genre        0
Developer    0
Publisher    0
dtype: int64

In [12]:
gsc

,Name,Sales,Series,Release,Genre,Developer,Publisher
0,PlayerUnknown's Battlegrounds,42.0,PlayerUnknown's Battlegrounds,2017-12-01,Battle royale,PUBG Studios,Krafton
1,Minecraft,33.0,Minecraft,2011-11-01,"Sandbox, survival",Mojang Studios,Mojang Studios
2,Diablo III,20.0,Diablo,2012-05-01,Action role-playing,Blizzard Entertainment,Blizzard Entertainment
3,Garry's Mod,20.0,Garry's Mod,2006-11-01,Sandbox,Facepunch Studios,Valve
4,Terraria,17.2,Terraria,2011-05-01,Action-adventure,Re-Logic,Re-Logic
...,...,...,...,...,...,...,...
170,Vietcong,1.0,Vietcong,2003-03-01,Tactical shooter,Pterodon,Gathering of Developers
171,Warhammer Online: Age of Reckoning,1.0,Warhammer,2008-09-01,MMORPG,Mythic Entertainment,Electronic Arts
172,Who Wants to Be a Millionaire?,1.0,Who Wants to Be a Millionaire?,1999-11-01,Trivia game,Jellyvision,Disney Interactive Studios
173,Wing Commander 3: Heart of the Tiger,1.0,Wing Commander,1994-12-01,Space combat simulation,Origin Systems,Electronic Arts
174,Zoo Tycoon,1.0,Zoo Tycoon,2001-10-01,Business simulation,Microsoft,Blue Fang Games

Change the data type in the 'Genre' column to a list, because there are several types of genres in certain games

In [13]:
def transform_to_list(x):
    if ',' in x:
        return x.split(',')
    else:
        return [x]

gsc.loc[:,('Genre')] = gsc['Genre'].apply(lambda x: transform_to_list(x))

In [14]:
gsc

,Name,Sales,Series,Release,Genre,Developer,Publisher
0,PlayerUnknown's Battlegrounds,42.0,PlayerUnknown's Battlegrounds,2017-12-01,[Battle royale],PUBG Studios,Krafton
1,Minecraft,33.0,Minecraft,2011-11-01,"[Sandbox, survival]",Mojang Studios,Mojang Studios
2,Diablo III,20.0,Diablo,2012-05-01,[Action role-playing],Blizzard Entertainment,Blizzard Entertainment
3,Garry's Mod,20.0,Garry's Mod,2006-11-01,[Sandbox],Facepunch Studios,Valve
4,Terraria,17.2,Terraria,2011-05-01,[Action-adventure],Re-Logic,Re-Logic
...,...,...,...,...,...,...,...
170,Vietcong,1.0,Vietcong,2003-03-01,[Tactical shooter],Pterodon,Gathering of Developers
171,Warhammer Online: Age of Reckoning,1.0,Warhammer,2008-09-01,[MMORPG],Mythic Entertainment,Electronic Arts
172,Who Wants to Be a Millionaire?,1.0,Who Wants to Be a Millionaire?,1999-11-01,[Trivia game],Jellyvision,Disney Interactive Studios
173,Wing Commander 3: Heart of the Tiger,1.0,Wing Commander,1994-12-01,[Space combat simulation],Origin Systems,Electronic Arts
174,Zoo Tycoon,1.0,Zoo Tycoon,2001-10-01,[Business simulation],Microsoft,Blue Fang Games

#File Exporting

Table is ready to use, now export the file

In [15]:
gsc.to_csv('game_sales_cleaned.csv')

from google.colab import files
files.download('game_sales_cleaned.csv')